const data = [
    {
        name: "User 1",
        companyId: "user1Id",
        country: "India",
        city: "Panipat",
        state: "Haryana",
        email: "user1@gmail.com",
        mobile: "8888888888",
        gstn: "HTUYT1234",
    },
    {
        name: "User 2",
        companyId: "user2Id",
        country: "India",
        city: "Panipat",
        state: "Haryana",
        email: "user2@gmail.com",
        mobile: "",
        gstn: "",
    },
    {
        name: "User 3",
        companyId: "user3Id",
        country: "India",
        city: "Panipat",
        state: "Haryana",
        email: "user3@gmail.com",
        mobile: "8888888888",
        gstn: "HTUYT3234",
    },
    {
        name: "User 4",
        companyId: "user4Id",
        country: "India",
        city: "Panipat",
        state: "Haryana",
        email: "user4@gmail.com",
        mobile: "8888888888",
        gstn: "HTUYT4234",
    },
    {
        name: "User 5",
        companyId: "user5Id",
        country: "India",
        city: "Panipat",
        state: "Haryana",
        email: "user5@gmail.com",
        mobile: "8888888888",
        gstn: "HTUYT5234",
    },
    {
        name: "User 6",
        companyId: "user6Id",
        country: "India",
        city: "Panipat",
        state: "Haryana",
        email: "user6@gmail.com",
        mobile: "8888888888",
        gstn: "HTUYT6234",
    },
    {
        name: "User 7",
        companyId: "user7Id",
        country: "India",
        city: "Panipat",
        state: "Haryana",
        email: "user7@gmail.com",
        mobile: "8888888888",
        gstn: "HTUYT7234",
    },
    {
        name: "User 8",
        companyId: "user8Id",
        country: "India",
        city: "Panipat",
        state: "Haryana",
        email: "user8@gmail.com",
        mobile: "8888888888",
        gstn: "HTUYT8234",
    },
    {
        name: "User 9",
        companyId: "user9Id",
        country: "India",
        city: "Panipat",
        state: "Haryana",
        email: "user9@gmail.com",
        mobile: "8888888888",
        gstn: "HTUYT9234",
    },
    
]

export const defaultDataVal = {
    country: "",
    city: "",
    state: "",
    email: "",
    mobile: "",
    gstn: "",
    backorder: "",
    paymentReminder: false,
    notification: false,
    sez: false,
    exportTax: false
}

export default data